name: C/C++ CI coverage and sanitize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./05_hw

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install dependencies
        run: sudo apt-get install -y gcovr lcov

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=True -DSTACKLIB_COVERAGE=ON

      - name: Build project and run ctest
        run: cmake --build build --target stack_test

      - name: Run ctest
        run: cmake --build build --target coverage

      - name: ls
        run: ls -lah ./coverage/

      - name: uppload cov report
        uses: actions/upload-artifact@v4
        with:
          name: cov-report
          path: 05_hw/coverage/

  analyze:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./05_hw

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install dependencies
        run: sudo apt-get install -y gcc g++ clang-tidy clang clang-tools

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=True -DCMAKE_BUILD_TYPE=Asan

      - name: Build project and run ctest
        run: cmake --build build --target main

      - name: Run analyze
        run: cmake --build build --target analyze

      - name: uppload clang-tidy report
        uses: actions/upload-artifact@v3
        with:
          name: clang-tidy-report
          path: build/analyzer/
